services:
    gateway-db:
        image: postgres:latest
        container_name: jl-gateway-db
        restart: always
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        ports:
            - '30300:5432'
        volumes:
            - gateway_db_data:/var/lib/postgresql/data

    game-db:
        image: postgres:latest
        container_name: jl-game-db
        restart: always
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
        ports:
            - '30301:5432'
        volumes:
            - game_db_data:/var/lib/postgresql/data

    player-db:
        image: postgres:latest
        container_name: jl-player-db
        restart: always
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
        ports:
            - '30302:5432'
        volumes:
            - player_db_data:/var/lib/postgresql/data

    board-db:
        image: postgres:latest
        container_name: jl-board-db
        restart: always
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
        ports:
            - '30303:5432'
        volumes:
            - board_db_data:/var/lib/postgresql/data

    eureka-db:
        image: postgres:latest
        container_name: jl-eureka-db
        restart: always
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
        ports:
            - '30304:5432'
        volumes:
            - eureka_db_data:/var/lib/postgresql/data

    rabbitmq:
        image: rabbitmq:3-management
        container_name: jl-rabbitmq
        ports:
            - '5672:5672'
            - '15672:15672'
        environment:
            RABBITMQ_DEFAULT_USER: guest
            RABBITMQ_DEFAULT_PASS: guest
        volumes:
            - rabbitmq_data:/var/lib/rabbitmq

volumes:
    gateway_db_data:
        driver: local
    game_db_data:
        driver: local
    player_db_data:
        driver: local
    board_db_data:
        driver: local
    eureka_db_data:
        driver: local
    rabbitmq_data:
        driver: local
