services:
    gateway-db:
        image: postgres:latest
        container_name: jl-gateway-db
        restart: always
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        ports:
            - '30300:5432'
        volumes:
            - gateway_db_data:/var/lib/postgresql/data
volumes:
    gateway_db_data:
        driver: local
