spring:
    application:
        name: gameservice

    jpa:
        hibernate:
            ddl-auto: update
        generate-ddl: true
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        show-sql: true

    datasource:
        driverClassName: org.postgresql.Driver
        url: jdbc:postgresql://localhost:30301/postgres
        username: postgres
        password: postgres

    rabbitmq:
        host: localhost
        port: 5672
        username: guest
        password: guest
        listener:
            simple:
                retry:
                    enabled: true
                    max-attempts: 3
                    initial-interval: 1000
                    multiplier: 2.0
                    max-interval: 10000

server:
    port: 30401

springdoc:
    api-docs:
        path: /game/v3/api-docs
    swagger-ui:
        enabled: true
        try-it-out-enabled: true

resilience4j:
    circuitbreaker:
        configs:
            default:
                failureRateThreshold: 50
                waitDurationInOpenState: 5000
                permittedNumberOfCallsInHalfOpenState: 3
                slidingWindowSize: 10
                minimumNumberOfCalls: 5
                automaticTransitionFromOpenToHalfOpenEnabled: true
                slidingWindowType: COUNT_BASED
        instances:
            boardClient:
                failureRateThreshold: 50
            gameClient:
                failureRateThreshold: 50
            playerClient:
                failureRateThreshold: 50

management:
    endpoints:
        web:
            exposure:
                include: health,circuitbreakers
    endpoint:
        health:
            show-details: always

eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:30404/eureka/
