services:
    postgres_db:
        image: postgres:latest
        container_name: jl-playerservice-db
        restart: always
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        ports:
            - '30302:5432'
        volumes:
            - postgres_db:/var/lib/postgresql/data
volumes:
    postgres_db:
        driver: local
